Feat: sso-react package
bcgov/cas-template-app pull request #31
Opened 2021-10-21 19:26 UTC by pbastia

A package providing a couple of front-end components and documentation, meant to be used with [sso-express](https://www.npmjs.com/package/@bcgov-cas/sso-express)

- [x] Session timeout handler
- [x] Logout warning modal
- [x] Session Refresher component
- [x] examples for login, logout and register buttons
- [x] documentation

2021-11-01 17:16 UTC, matthieu-foucault requested changes

2021-11-01 17:16 UTC, matthieu-foucault commented on packages/sso-react/src/SessionRefresher.tsx
> +  refreshUrl,
should default to `/extend-session`

2021-11-01 17:16 UTC, matthieu-foucault commented on packages/sso-react/README.md
> +        refreshUrl="/session-idle-remaining-time"
```suggestion
        refreshUrl="/extend-session"
```

2021-11-02 15:50 UTC, pbastia commented on packages/sso-react/README.md
> +        refreshUrl="/session-idle-remaining-time"
good catch

2021-11-02 16:19 UTC, matthieu-foucault requested changes

2021-11-02 16:28 UTC, pbastia commented on packages/sso-react/tsconfig.json
> +    "types": ["jest", "jest-extended"]
we do for the `yarn test` directive to work, that other tsconfig file is for VSCode only

2021-11-17 00:00 UTC, matthieu-foucault requested changes
Just a couple of documentation updates needed

2021-11-22 20:36 UTC, matthieu-foucault approved these changes
Merging this prior to `sso-express` rewrite

2021-11-22 20:36 UTC, merged